apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list-webapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-list-webapp
    spec:
      containers:
        - image: todolist-webapp:0.0.5
          name: todolist-webapp
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
